### ISSUE TITLE
Didn't build

### ISSUE THREAD

**Issue by JonathanNYC** [gergelyorosz/swift-objective-c-mixed-project#1]
I got this build error using the file I downloaded on Xcode 7.2.  

/Users/.../Developer/swift-objective-c-mixed-project-master/MixedLanugageExample/MixedLanugageExample/LabelObjectiveC.m:10:9: 'MixedLanugageExample-Swift.h' file not found

```
                                         * * * Update * * *
```

I posted the above yesterday.  Subsequently, I experienced a variety of changing error messages.
I eliminating the test files from the project & the build process seems much better now.  
Hopefully, I will now be able to use this example in my own project.

**Comment by gergelyorosz** [comment]
Thanks @JonathanNYC . I could repro another build issue that I fixed. Hopefully this resolves your issue?
